# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
com-alpsbte-alpslib-alpslib-io = "1.2.1" # https://mvn.alps-bte.com/service/rest/repository/browse/alps-bte/com/alpsbte/alpslib/alpslib-io/
com-alpsbte-alpslib-alpslib-utils = "1.4.1" # https://mvn.alps-bte.com/service/rest/repository/browse/alps-bte/com/alpsbte/alpslib/alpslib-utils/
com-sk89q-worldguard-worldguard-bukkit = "7.0.15" # https://maven.enginehub.org/repo/com/sk89q/worldguard/worldguard-bukkit/
io-papermc-paper-paper-api = "1.21.10-R0.1-SNAPSHOT" # https://artifactory.papermc.io/ui/native/universe/io/papermc/paper/paper-api/
li-cinnazeyy-langlibs-api = "1.5.2" # https://mvn.alps-bte.com/service/rest/repository/browse/alps-bte/li/cinnazeyy/LangLibs-API/
org-spongepowered-configurate-yaml = "4.2.0" # https://github.com/SpongePowered/Configurate/releases
shadow = "9.3.1" # https://github.com/GradleUp/shadow/releases

[libraries]
com-alpsbte-alpslib-alpslib-io = { module = "com.alpsbte.alpslib:alpslib-io", version.ref = "com-alpsbte-alpslib-alpslib-io" }
com-alpsbte-alpslib-alpslib-utils = { module = "com.alpsbte.alpslib:alpslib-utils", version.ref = "com-alpsbte-alpslib-alpslib-utils" }
com-sk89q-worldguard-worldguard-bukkit = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "com-sk89q-worldguard-worldguard-bukkit" }
io-papermc-paper-paper-api = { module = "io.papermc.paper:paper-api", version.ref = "io-papermc-paper-paper-api" }
li-cinnazeyy-langlibs-api = { module = "li.cinnazeyy:LangLibs-API", version.ref = "li-cinnazeyy-langlibs-api" }
org-spongepowered-configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "org-spongepowered-configurate-yaml" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

